---
# tasks file for httpd "RedHat"

- name: httpd-RedHat-setup | Check the OS Family.
  fail: msg="You can not perform the task in this OS family '{{ ansible_os_family }}'."
  when: ansible_os_family != "RedHat"
  tags:
  - always

- name: httpd-RedHat-setup | Set facts Packages
  set_fact:
    httpd_install_packages: [ 'httpd' ]
  when: httpd_install_packages|d(none) is none
  tags:
  - always

- name: httpd-RedHat-setup | Install the httpd
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ httpd_install_packages }}"
  tags:
  - httpd
  - httpd-install
  - httpd-RedHat
  - httpd-RedHat-install

