---
# taska/defaults.yml
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- block:

  - name: "platforms | defaults | Load the defaults vars for platforms."
    set_fact:
      platforms_defaults_file: "{{ _defaults_file|basename }}"
      platforms_defaults_vars: |-
        {%- set o = {} -%}
        {%- set _defaults_vars = lookup('file',_defaults_file)|from_yaml -%}
        {%- if _export == true or _export_var|d('')|string|trim|length > 0 -%}
        {%    set _e = _export_var
                  if _export_var|d('')|string|trim|length > 0
                  else none %}
        {%    set _ = vars.update({ _e:{} })
                  if _e is not none
                  else none %}
        {%    for _k, _v in (_defaults_vars|d({}))|dictsort
                  if (_k|d(''))|string|trim|length > 0 %}
        {%      if _e is not none and o[_e] is defined %}
        {%        set _ = o[_e].update({ _k:_v }) %}
        {%      elif (_e is none)
                and (vars[_k]|d(none) is none
                 or (vars[_k] is iterable and vars[_k]|length <= 0)) %}
        {%        set _ = o.update({ _k:_v }) %}
        {%      endif %}
        {%    endfor %}
        {%- endif -%}
        {{- o -}}
    with_first_found:
    - files:
      - "{{ '%s/platforms_%s_%s_%s.yml'|format(_r_path,_p.family,_p.dist,_p.major) }}"
      - "{{ '%s/platforms_%s_%s.yml'|format(_r_path,_p.family,_p.dist) }}"
      - "{{ '%s/platforms_%s.yml'|format(_r_path,_p.family) }}"
      - "{{ '%s/%s_%s_%s.yml'|format(_r_path,_p.family,_p.dist,_p.major) }}"
      - "{{ '%s/%s_%s.yml'|format(_r_path,_p.family,_p.dist) }}"
      - "{{ '%s/%s.yml'|format(_r_path,_p.family) }}"
      - "{{ '%s/platforms_default.yml'|format(_r_path) }}"
      - "{{ '%s/default.yml'|format(_r_path) }}"
      skip: yes
    loop_control:
      loop_var: _defaults_file

  - name: "platforms | defaults | Exports defaults vars for platforms."
    set_fact: "{{ item.key }}={{ item.value }}"
    with_dict: "{{
      platforms_defaults_vars
      if _export|bool == true and platforms_defaults_vars|d(none) is not none
      else {} }}"
    when: item.key|d(none) is not none

  when: (platforms_defaults_path|d(path|d('')))|is_dir
        and (ansible_os_family|d(''))|string|length > 0
  vars:
    platforms_defaults_file:
    platforms_defaults_vars:
    _r_path: "{{
      '%s'|format(platforms_defaults_path|d(path|d('.')))
      if ansible_os_family|d('')|string|length > 0
      else '_' }}"
    _export: "{{
      ansible_os_family|d('')|string|length > 0
      and ( platforms_exports_vars|d(exports|d(false))|bool == true
         or platforms_exports_vars|d(exports|d(''))|string|trim|length > 0 ) }}"
    _export_var: "{{
      platforms_exports_vars|d(exports|d(''))|string|trim
      if ansible_os_family|d('')|string|length > 0
      and platforms_exports_vars|d(exports|d(false))|bool == false
      else '' }}"
    _p:
      family: "{{ ansible_os_family|d('')|string|lower }}"
      dist: "{{ ansible_distribution|d('')|string|lower }}"
      major: "{{ ansible_distribution_major_version|d('')|string|lower }}"

