---
# tasks file for resolver

- name: resolver| Updating /etc/resolv.conf
  template:
    src: "etc/resolv.conf.j2"
    dest: "{{ prefix_dir|d('') }}/etc/resolv.conf"
    owner: "{{ test_owner|d('root') }}"
    group: "{{ test_group|d('root') }}"
    mode: "0644"
    backup: yes
  tags:
  - resolver

