---
# tasks file for resolver
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- name: "resolver| Updating /etc/resolv.conf"
  template:
    src: "etc/resolv.conf.j2"
    dest: "{{
        '%s%s'|format(tests_prefix_dir|d(''),
        (resolver_resolv_conf_file|d({})).path|d(
        resolver_resolv_conf_file|d('/etc/resolv.conf'))) }}"
    owner: "{{
        tests_owner|d(
        (resolver_resolv_conf_file|d({})).owner|d(
        resolver_resolv_conf_file_owner|d('root'))) }}"
    group: "{{
        tests_owner|d(
        (resolver_resolv_conf_file|d({})).group|d(
        resolver_resolv_conf_file_group|d('root'))) }}"
    mode: "{{
        '%04o'|format(
        (resolver_resolv_conf_file|d({})).mode|d(
        resolver_resolv_conf_file_mode|d('0644'))|int(base=8)) }}"
    backup: "{{ tests_run|d(false)|bool == false }}"
  when: platforms_supported|d(false)|bool == true
        and ( (resolver_domain|d(none) is string
           and resolver_domain|trim|length > 0)
           or (resolver_search_domain|d(none) is string
           and resolver_search_domain|trim|length > 0)
           or (resolver_nameservers|d(none) is iterable
           and resolver_nameservers|length > 0)
           or (resolver_sortlist|d(none) is iterable
           and resolver_sortlist|length > 0)
           or (resolver_options|d(none) is iterable
           and resolver_options|length > 0) )
  tags:
  - resolver

