---
# tasks file for syslog

- name: syslog | Include OS/Distribution specific variables.
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
  - "{{ '%s-%s.yml'|format(os_spec_os_family,os_spec_os_distribution) }}"
  - "{{ '%s.yml'|format(os_spec_os_family) }}"
  - "default.yml"
  tags:
  - syslog
  - syslog-include-vars

- name: "syslog | Install package"
  include: "{{ item }}"
  with_first_found:
  - "{{ '%s-%s.yml'|format(os_spec_os_family,os_spec_os_distribution) }}"
  - "{{ '%s.yml'|format(os_spec_os_family) }}"
  - "default.yml"
  tags:
  - syslog
  - syslog-syslog-install

- name: "syslog | Updating {{ syslog_syslog_conf }}"
  include: syslog-conf.yml
  tags:
  - syslog
  - syslog-conf
