---
# tasks file for syslog
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- block:

  - name: "syslog | The path of this role."
    command: echo {{ role_path|quote }}
    register: from_role_path
    changed_when: no
    check_mode: no

  - name: "syslog | Platform specific initialization processing."
    include_role:
      name: platforms
      tasks_from: setup

  tags:
  - syslog
  - syslog-setup

- name: "syslog | Updating {{ syslog_syslog_conf|d('???') }}"
  include: syslog-conf.yml
  when: syslog_syslog_conf|d('')|string|trim|length > 0
  tags:
  - syslog
  - syslog-conf
