---
# tasks file for syslog of "redhat"
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- name: "syslog | redhat | Install the syslog"
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ syslog_install_packages|d([]) }}"
  when: tests_run|d(false) == false
        and item|d(none) is string and item|trim|length > 0
  notify:
  - syslog-enable-syslog
  tags:
  - syslog
  - syslog-install
  - syslog-redhat
  - syslog-redhat-install

