---
# tasks file for syslog "RedHat"

- name: syslog-RedHat-setup | Check the OS Family.
  fail: msg="You can not perform the task in this OS family '{{ ansible_os_family }}'."
  when: ansible_os_family != "RedHat"
  tags:
  - always

- name: syslog-RedHat-setup | Check the type of syslog.
  set_fact:
    __syslog_type: "{{ 'rsyslog' if ansible_distribution_major_version >= 6 else 'syslog' }}"
  tags:
  - always

- name: syslog-RedHat-setup | Set facts type and conf path.
  set_fact:
    syslog_syslog_type: "{{ __syslog_type }}"
    syslog_syslog_conf: "/erc/{{ __syslog_type }}.conf"
  when: __syslog_type|d(none) is not none
  tags:
  - always

- name: "syslog-RedHat-setup | Install the {{ syslog_syslog_type }}"
  yum:
    name: "{{ syslog_syslog_type }}"
    state: latest
  when: syslog_syslog_type|d(none) is not none
        or syslog_syslog_conf|d(none) is not none
  notify:
  - syslog-enable-syslog
  tags:
  - syslog
  - syslog-install
  - syslog-RedHat
  - syslog-RedHat-install

