---
# tasks 'add-hosts-acls' file for etc-hosts
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- block:

  - name: "etc-hosts | add-hosts-acls | Update '/etc/hosts.{allow|deny}'."
    include: '_etc_hosts_hosts-acls.yml'

  when: platforms_supported|d(false)|bool == true
        and etc_hosts_acls_entries|d(none) is not none
        and ((etc_hosts_using_hosts_allow|d(true) == true
          and etc_hosts_acls_entries.allow|d(none) is iterable
          and etc_hosts_acls_entries.allow is not string
          and etc_hosts_acls_entries.allow|length > 0)
          or (etc_hosts_using_hosts_deny|d(true) == true
          and etc_hosts_acls_entries.deny|d(none) is iterable
          and etc_hosts_acls_entries.deny is not string
          and etc_hosts_acls_entries.deny|length > 0)
          or (etc_hosts_specific_hosts|d(none) is mapping
          and etc_hosts_specific_hosts|dictsort|length > 0))
  tags:
  - etc-hosts-acls

