---
# tasks 'add-hosts' file for etc-hosts
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- block:

  - name: "etc-hosts | add-hosts | Update '/etc/hosts'."
    include: '_etc_hosts_hosts.yml'

  when: platforms_supported|d(false)|bool == true
        and etc_hosts_hosts_items|d(none) is iterable
        and etc_hosts_hosts_items is not string
        and etc_hosts_hosts_items|length > 0
        and (etc_hosts_using_ipv4|d(true) == true
          or etc_hosts_using_ipv6|d(true) == true)
  vars:
    etc_hosts_hosts_items: |-
      {%- set o = etc_hosts_hosts_for_hosts
              if etc_hosts_hosts_for_hosts|d(none) is mapping
              else {} -%}
      {%- set _ = o.update({
              'default':(etc_hosts_hosts
              if etc_hosts_hosts|d(none) is iterable
              and etc_hosts_hosts is not string
              else []) }) -%}
      {{- o -}}
  tags:
  - etc-hosts-hosts

