---
# tasks 'add-hosts-acls' file for etc-hosts
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- block:

  - name: "etc-hosts | add-hosts-acls | Update '/etc/hosts.{allow|deny}'."
    include: '_etc_hosts_hosts-acls.yml'

  when: platforms_supported|d(false)|bool == true
        and etc_hosts_hosts_acl_items|d(none) is mapoing
        and (etc_hosts_using_hosts_allow|d(true) == true
          or etc_hosts_using_hosts_deny|d(true) == true)
  vars:
    etc_hosts_hosts_acl_items: |-
      {%- set o = etc_hosts_hosts_acls_for_hosts
              if etc_hosts_hosts_for_hosts|d(none) is mapping
              else {} -%}
      {%- set _ = o.update({
              'default':{
                'allow':(etc_hosts_hosts_acls
                  if etc_hosts_hosts_acls|d(none) is mapping
                  and etc_hosts_hosts_acls.allow|d(none) is iterable
                  else []),
                'deny':(etc_hosts_hosts_acls
                  if etc_hosts_hosts_acls|d(none) is mapping
                  and etc_hosts_hosts_acls.deny|d(none) is iterable
                  else []) } }) -%}
        {{- o -}}
  tags:
  - etc-hosts-acls

