---
# tasks 'add-hosts' file for etc-hosts
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- block:

  - name: "etc-hosts | add-hosts | Update '/etc/hosts'."
    include: '_etc_hosts_hosts.yml'

  when: platforms_supported|d(false)|bool == true
        and ((etc_hosts_hosts|d(none) is iterable
          and etc_hosts_hosts is not string
          and etc_hosts_hosts|length > 0)
          or (etc_hosts_specific_hosts|d(none) is mapping
          and etc_hosts_specific_hosts|dictsort|length > 0))
        and (etc_hosts_using_ipv4|d(true) == true
          or etc_hosts_using_ipv6|d(true) == true)
  tags:
  - etc-hosts-hosts

