---
# tasks file for etc-hosts
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- block:

  - name: "etc-hosts | Updating /etc/hosts"
    template:
      src: "etc/hosts.j2"
      dest: "{{ tests_prefix_dir|d('') }}/etc/hosts"
      owner: "{{ tests_owner|d('root') }}"
      group: "{{ tests_group|d('root') }}"
      mode: "0644"
      backup: "{{ tests_run|d(false) == false }}"
    when: (etc_hosts_using_ipv4|d(true) == true
          or etc_hosts_using_ipv6|d(true) == true)
    tags:
    - etc-hosts

  vars:
    etc_hosts: |
      {%  set o = { 'hosts':[], 'allow':[], 'deny':[] } %}
      {%  set _etc_hosts = etc_hosts_hosts
              if etc_hosts_hosts|d(none) is mapping else {} %}
      {%  set _hname = inventory_hostname_short|lower
              if inventory_hostname_short|d('')|string|trim|length > 0
              else inventory_hostname|d('')|string|lower %}
      {%  if _etc_hosts.default|d(none) is not none
          and ( _etc_hosts.hosts|d(none) is not none
             or _etc_hosts.allow|d(none) is not none
             or _etc_hosts.deny|d(none) is not none ) %}
      {%    set _hosts = _etc_hosts.hosts
                if _etc_hosts.hosts|d(none) is not none else none %}
      {%    set _hallow = _etc_hosts.allow
                if _etc_hosts.allow|d(none) is not none else none %}
      {%    set _hdeny = _etc_hosts.deny
                if _etc_hosts.deny|d(none) is not none else none %}
      {%    set _ = _etc_hosts.update({
                'default':{ 'hosts':_hosts, 'allow':_hallow, 'deny':_hdeny } }) %}
      {%  endif %}
      {%  set _hents = [_etc_hosts[_hname]]
              if ((_etc_hosts|d({}))[_hname])|d(none) is not none
              else [] %}
      {%  set _grnames = (group_names|d([])|sort)|union(['default','all']) %}
      {%  for __grname in _grnames|d([])
              if __grname|lower not in [ _hname ]
              and ((_etc_hosts|d({}))[__grname|lower])|d(none) is not none %}
      {%    set _ = _hents.append( _etc_hosts[__grname|lower] ) %}
      {%  endfor %}
      {%  for _h_ent in _hents|d([])
              if (_h_ent|d(none) is iterable and _h_ent is not string)
              or (_h_ent.hosts|d(none) is iterable and _h_ent.hosts is not string)
              or (_h_ent.allow|d(none) is iterable and _h_ent.allow is not string)
              or (_h_ent.deny|d(none) is iterable and _h_ent.deny is not string) %}
      {%    if (_h_ent|d(none) is iterable and _h_ent is not string)
            or (_h_ent.hosts|d(none) is iterable and _h_ent.hosts is not string) %}
      {%      set _ = o.update({ 'hosts':((o.hosts) + (_h_ent.hosts|d(_h_ent))) }) %}
      {%    endif %}
      {%    if (_h_ent.allow|d(none) is iterable and _h_ent.allow is not string) %}
      {%      set _ = o.update({ 'allow':((o.allow) + (_h_ent.allow)) }) %}
      {%    endif %}
      {%    if (_h_ent.deny|d(none) is iterable and _h_ent.deny is not string) %}
      {%      set _ = o.update({ 'deny':((o.deny) + (_h_ent.deny)) }) %}
      {%    endif %}
      {%  endfor %}
      {{- o -}}
  when: platforms_supported|d(false) == true

