---
# tasks file for etc-hosts
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- block:

  - name: etc-hosts | Updating /etc/hosts
    template:
      src: "etc/hosts.j2"
      dest: "{{ tests_prefix_dir|d('') }}/etc/hosts"
      owner: "{{ tests_owner|d('root') }}"
      group: "{{ tests_group|d('root') }}"
      mode: "0644"
      backup: "{{ tests_run|d(false) == false }}"
    when: (etc_hosts_using_ipv4|d(true) == true
          or etc_hosts_using_ipv6|d(true) == true)
    tags:
    - etc-hosts

  - name: etc-hosts | Updating /etc/hosts.allow
    template:
      src: "etc/hosts.allow.j2"
      dest: "{{ tests_prefix_dir|d('') }}/etc/hosts.allow"
      owner: "{{ tests_owner|d('root') }}"
      group: "{{ tests_group|d('root') }}"
      mode: "0644"
      backup: "{{ tests_run|d(false) == false }}"
    when: etc_hosts_using_hosts_allow|d(true) == true
    tags:
    - etc-hosts-allow

  - name: etc-hosts | Updating /etc/hosts.deny
    template:
      src: "etc/hosts.deny.j2"
      dest: "{{ tests_prefix_dir|d('') }}/etc/hosts.deny"
      owner: "{{ tests_owner|d('root') }}"
      group: "{{ tests_group|d('root') }}"
      mode: "0644"
      backup: "{{ tests_run|d(false) == false }}"
    when: etc_hosts_using_hosts_deny|d(true) == true
    tags:
    - etc-hosts-deny

  vars:
    etc_hosts: |
      {%  set o = { 'hosts':[], 'allow':[], 'deny':[] } %}
      {%  set _hname = inventory_hostname_short|lower
              if inventory_hostname_short|d('')|string|trim|length > 0
              else inventory_hostname|d('')|string|lower %}
      {%  set _hents = [etc_hosts_hosts[_hname]]
              if ((etc_hosts_hosts|d({}))[_hname])|d(none) is not none
              else [] %}
      {%  set _grnames = (group_names|d([])|sort)|union(['default','all']) %}
      {%  for __grname in _grnames|d([])
              if __grname|lower not in [ _hname ]
              and ((etc_hosts_hosts|d({}))[__grname|lower])|d(none) is not none %}
      {%    set _ = _hents.append( etc_hosts_hosts[__grname|lower] ) %}
      {%  endfor %}
      {%  for _h_ent in _hents|d([])
              if (_h_ent|d(none) is iterable and _h_ent is not string)
              or (_h_ent.hosts|d(none) is iterable and _h_ent.hosts is not string)
              or (_h_ent.allow|d(none) is iterable and _h_ent.allow is not string)
              or (_h_ent.deny|d(none) is iterable and _h_ent.deny is not string) %}
      {%    if (_h_ent|d(none) is iterable and _h_ent is not string)
            or (_h_ent.hosts|d(none) is iterable and _h_ent.hosts is not string) %}
      {%      set _ = o.update({ 'hosts':((o.hosts) + (_h_ent.hosts|d(_h_ent))) }) %}
      {%    endif %}
      {%    if (_h_ent.allow|d(none) is iterable and _h_ent.allow is not string) %}
      {%      set _ = o.update({ 'allow':((o.allow) + (_h_ent.allow)) }) %}
      {%    endif %}
      {%    if (_h_ent.deny|d(none) is iterable and _h_ent.deny is not string) %}
      {%      set _ = o.update({ 'deny':((o.deny) + (_h_ent.deny)) }) %}
      {%    endif %}
      {%  endfor %}
      {{- o -}}

