---
# handlers file for syslog

- name: syslog-enable-syslog
  service:
    name: syslog
    enabled: yes
  when: test_run|d(none) is none

- name: syslog-start-syslog 
  service:
    name: syslog
    state: started
  when: test_run|d(none) is none

- name: syslog-restart-syslog
  service:
    name: syslog
    state: restarted
  when: test_run|d(none) is none

