---
# tasks 'logrotate-dropin-file' file for logrotate
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- block:

  - name: "logrotate | logrotate-dropin-file | Create include directory '{{ _dropins_dir }}'."
    file:
      path: "{{ '%s%s'|format(tests_prefix_dir|d(''),_dropins_dir) }}"
      state: directory
      owner: "{{ tests_owner|d(_dropins_dir_owner) }}"
      group: "{{ tests_group|d(_dropins_dir_group) }}"
      mode: "{{ _dropins_dir_mode }}"

  - name: "logrotate | logrotate-dropin-file | Create logrotate file under the '{{ _dropins_dir }}'."
    template:
      src: "etc/logrotate.dropin.file.j2"
      dest: "{{ '%s%s'|format(tests_prefix_dir|d(''),_dropin_file_path) }}"
      owner: "{{ tests_owner|d(_dropin_file_owner) }}"
      group: "{{ tests_group|d(_deopin_file_group) }}"
      mode: "{{ _dropin_file_mode }}"
    vars:
      _dropin_file_path: "{{
        '%s/%s'|format(_dropin_dir,logrotate_dropin_file.name) }}"
      _dropin_file_owner: "{{
        logrotate_dropin_file.owner|trim
        if logrotate_dropin_file.owner|d(none) is string
        and logrotate_dropin_file.owner|trim|length > 0
        else _dropin_dir_owner }}"
      _dropin_file_group: "{{
        logrotate_dropin_file.group|trim
        if logrotate_dropin_file.group|d(none) is string
        and logrotate_dropin_file.group|trim|length > 0
        else _dropin_dir_group }}"
      _dropin_file_mode: "{{
        '%04o'|format(
        logrotate_dropin_file.mode|int(base=8)
        if logrotate_dropin_dir.mode|d(none) is not none
        and logrotate_dropin_dir.mode|string|trim|length > 0
        else logrotate_conf_file.mode|int(base=8)
        if logrotate_conf_file|d(none) is mapping
        and logrotate_conf_file.mode|d(none) is not none
        and logrotate_conf_file.mode|string|trim|length > 0
        else logrotate_conf_file_mode|int(base=8)
        if logrotate_conf_file_mode|d(none) is not none
        and logrotate_conf_file_mode|string|trim|length > 0
        else '0644'|int(base=8)) }}"

  when: (logrotate_dropin_dir|d(logrotate_include_dir|d(none))) is not none
        and ((logrotate_dropin_dir|d(logrotate_include_dir))|string|trim|lower|
             match('^(no|false)$') == false)
        and logrotate_dropin_file|d(none) is mapping
        and logrotate_dropin_file.name|d(none) is string
        and logrotate_dropin_file.name|trim|length > 0
        and logrotate_dropin_file.logfiles|d(none) is string
        and logrotate_dropin_file.logfiles|trim|length > 0
  vars:
    _dropin _dir: "{{
      (logrotate_dropin_dir|d(logrotate_include_dir)).path|trim
      if (logrotate_dropin_dir|d(logrotate_include_dir|d(none))) is mapping
      and (logrotate_dropin_dir|d(logrotate_include_dir)).path|d(none) is string
      and (logrotate_dropin_dir|d(logrotate_include_dir)).path|trim|length > 0
      else (logrotate_dropin_dir|d(logrotate_include_dir))|trim
      if (logrotate_dropin_dir|d(logrotate_include_dir|d(none))) is string
      and (logrotate_dropin_dir|d(logrotate_include_dir))|trim|length > 0
      else '/etc/logrotate.d' }}"
    _deopin_dir_owner: "{{
      (logrotate_dropin_dir|d(logrotate_include_dir)).owner|trim
      if (logrotate_dropin_dir|d(logrotate_include_dir|d(none))) is mapping
      and (logrotate_dropin_dir|d(logrotate_include_dir)).owner|d(none) is string
      and (logrotate_dropin_dir|d(logrotate_include_dir)).owner|trim|length > 0
      else logrotate_dropin_dir_owner|trim
      if logrotate_dropin_dir_owner|d(none) is string
      and logrotate_dropin_dir_owner|trim|length > 0
      else logrotate_conf_file.owner|trim
      if logrotate_conf_file|d(none) is mapping
      and logrotate_conf_file.owner|d(none) is string
      and logrotate_conf_file.owner|trim|length > 0
      else logrotate_conf_file_owner|trim
      if logrotate_conf_file_owner|d(none) is string
      and logrotate_conf_file_owner|trim|length > 0
      else 'root' }}"
    _dropin_dir_group: "{{
      (logrotate_dropin_dir|d(logrotate_include_dir)).group|trim
      if (logrotate_dropin_dir|d(logrotate_include_dir|d(none))) is mapping
      and (logrotate_dropin_dir|d(logrotate_include_dir)).group|d(none) is string
      and (logrotate_dropin_dir|d(logrotate_include_dir)).group|trim|length > 0
      else logrotate_dropin_dir_group|trim
      if logrotate_dropin_dir_group|d(none) is string
      and logrotate_dropin_dir_group|trim|length > 0
      else logrotate_conf_file.group|trim
      if logrotate_conf_file|d(none) is mapping
      and logrotate_conf_file.group|d(none) is string
      and logrotate_conf_file.group|trim|length > 0
      else logrotate_conf_file_group|trim
      if logrotate_conf_file_group|d(none) is string
      and logrotate_conf_file_group|trim|length > 0
      else 'root' }}"
    _dropin_dir_mode: "{{
      '%04o'|format(
      (logrotate_dropin_dir|d(logrotate_include_dir)).mode|int(base=8)
      if (logrotate_dropin_dir|d(logrotate_include_dir|d(none))) is mapping
      and (logrotate_dropin_dir|d(logrotate_include_dir)).mode|d(none) is not none
      and (logrotate_dropin_dir|d(logrotate_include_dir)).mode|string|trim|length > 0
      else logrotate_dropin_dir_mode|int(base=8)
      if logrotate_dropin_dir_mode|d(none) is not none
      and logrotate_dropin_dir_mode|string|trim|length > 0
      else '0755'|int(base=8)) }}"
  tags:
  - logrotate-dropin-file

