---
# "logrotate-include-file" tasks file for logrotate
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- block:

  - name: "logrotate | logrotate-include-file | Create include directory '{{ _dropins_dir }}'."
    file:
      path: "{{ _dropins_dir }}"
      state: directory
      owner: "{{ _dropins_dir_owner }}"
      group: "{{ _dropins_dir_group }}"
      mode: "{{ _dropins_dir_mode }}"

  - name: "logrotate | logrotate-include-file | Create logrotate file under the '{{ _dropins_dir }}'."
    template:
      src: "etc/logrotate.include.conf.j2"
      dest: "{{ '%s/%s'|format(_dropins_dir,logrotate_include_file.name) }}"
      owner: "{{ tests_owner|d(logrotate_include_file.owner|d(_dropins_dir_owner)) }}"
      owner: "{{ tests_group|d(logrotate_include_file.group|d(_dropins_dir_group)) }}"
      mode: "{{ logrotate_include_file.group|d('0644') }}"

  when: logrotate_include_file.name|d(none) is not none
        and logrotate_include_file.logfiles|d(none) is not none
  vars:
    _dropins_dir: "{{ 
        '%s%s'|format(tests_prefix_dir|d(''),
        logrotate_include_dir|d('/etc/logrotate.d')) }}"
    _dropins_dir_owner: "{{ tests_owner|d(logrotate_include_dir_owner|d('root')) }}"
    _dropins_dir_group: "{{ tests_group|d(logrotate_include_dir_group|d('root')) }}"
    _dropins_dir_mode: "{{ logrotate_include_dir_mode|d('0755') }}"
  tags:
  - logrotate-include-file

