---
# tasks file for logrotate
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- block:

  - name: "logrotate | The path of this role."
    command: echo {{ role_path|quote }}
    register: from_role_path
    changed_when: no
    check_mode: no

  - name: "logrotate | Platform specific initialization processing."
    include_role:
      name: platforms
      tasks_from: setup

  tags:
  - logrotate
  - logrotate-setup

- name: "logrotate | Updating logrotate configuration."
  template:
    src: "etc/logrotate.conf.j2"
    dest: "{{ '%s%s'|format(tests_prefix_dir|d(''),
              (logrotate_conf_file|d({})).path|d(
              logrotate_conf_file|d('/etc/logrotate.conf'))) }}"
    owner: "{{ tests_owner|d(
               (logrotate_conf_file|d({})).owner|d(
               logrotate_conf_file_owner|d('root'))) }}"
    group: "{{ tests_group|d(
               (logrotate_conf_file|d({})).group|d(
               logrotate_conf_file_group|d('root'))) }}"
    mode: "{{ '%04o'|format(
              (logrotate_conf_file|d({})).mode|d(
              logrotate_conf_file_mode|d('0644'))|int(base=8)) }}"
    backup: "{{ tests_run|d(false)|bool == false }}"
  tags:
  - logrotate
  - logrotate-conf

- block:

  - name: "logrotate | Updating dropin files."
    include: logrotate-dropin-file.yml
    with_items: "{{ logrotate_dropin_files|d(logrotate_include_files|d([])) }}"
    loop_control:
      loop_var: logrotate_dropin_file
    when: logrotate_dropin_file|d(none) is mapping 
          and logrotate_dropin_file.name|d(none) is string
          and logrotate_dropin_file.logfiles|d(none) is string

  when: logrotate_dropin_dir|d(logrotate_include_dir|d(none)) is not none
        and (logrotate_dropin_dir|d(logrotate_include_dir)|string|lower)|
             match('^[ ]*(no|false)[ ]*$') == false
  tags:
  - logrotate
  - logrotate-dropin-files

