---
# defaults file for rsyslog (default)

# Rsyslog install packages
rsyslog_install_packages:
  - rsyslog

# Rsyslog service name
rsyslog_service_name: rsyslog

# Rsyslog conf
rsyslog_rsyslog_conf: /etc/rsyslog.conf

# Rsyslog modules
rsyslog_conf_modules:
  - imuxsock.so:
    comment: provides support for local system logging (e.g. via logger command)
  - imklog.so:
    comment: provides kernel logging support (previously done by rklogd)
  - immark.so:
    comment: provides --MARK-- message capability

# Rsyslog directives
rsyslog_conf_directives:
  - $ActionFileDefaultTemplate: RSYSLOG_TraditionalFileFormat
    comment: Use default timestamp format

# Rsyslog rules
rsyslog_conf_rules:
  - selectors:
    - "kern.*"
    - "kern.!=debug"
    destination: "/var/log/kern.log"
    comment: |
      Log all kernel messages.
  - selectors: "*.emerg"
    destination: "*"
    comment: Everybody gets emergency messages.
  - selectors:
    - "*.info"
    - "authpriv,cron,daemon,mail.none"
    destination: "-/var/log/messages"
    comment: |
      Log anything (except mail) of level info or higher.
      Don't log private authentication messages!
  - selectors: "authpriv.*"
    destination: "-/var/log/secure"
    comment: "The authpriv file has restricted access."
  - selectors: "cron.*"
    destination: "-/var/log/cron"
    comment: "Log cron stuff"
  - selectors: "daemon.*"
    destination: "-/var/log/daemon.log"
    comment: "daemon"
  - selectors: "mail.*"
    destination: "-/var/log/maillog"
    comment: "Log all the mail messages in one place."
  - selectors: "uucp,news.crit"
    destination: "-/var/log/spooler"
    comment: "Save news errors of level crit and higher in a special file."

