---
# os-spec.yml
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- block:

  - name: "os-spec | Check the OS and Version."
    fail:
      msg: |
        {{ 'Unsupported OS: %s-%s v%s; Not in cond[ %s ].'|format(
           __os_family|d('none'),__os_dist|d('none'),os_spec_os_version|d('n/a'),
           (os_spec|d({})|string)) }}
    ignore_errors: "{{ os_spec_ignore_errors|d(false) }}"
    register: os_spec_supported
    when: ( __os_family|d(none) is not none and __os_dist|d(none) is not none
            and ( __os_vers.min|d(none) is not none
               or __os_vers.max|d(none) is not none ) )
          and
          ( ( ( __os_vers|d(none) is iterable and __os_vers|d(none) is not string )
              and ( os_spec_os_major_version in __os_vers
                 or os_spec_os_version in __os_vers ) )
            or
            ( __os_vers.min|d(none) is not none
              and os_spec_os_version|d('0.0')|
                  version_compare(__os_vers.min|d('0.0'),'<') )
            or
            ( __os_vers.max|d(none) is not none
              and os_spec_os_version|d('99999.999')|
                  version_compare(__os_vers.max|d('99999.999'),'>') ) )

  when: os_spec|d(none) is not none
  tags:
  - os-spec-verify

