---
# tasks file for sysctl

- name: sysctl | Updating /etc/sysctl.conf
  template:
    src: "etc/sysctl.conf.j2"
    dest: "{{ '%s%s'|format(prefix_dir|d(''),sysctl_conf_path|d('/etc/sysctl.conf')) }}"
    owner: "{{ test_owner|d( sysctl_conf_owner|d('root') ) }}"
    group: "{{ test_group|d( sysctl_conf_group|d('root') ) }}"
    mode: "{{ sysctl_conf_mode|d('0644') }}"
    backup: yes
  tags:
  - sysctl

