---
# tasks file for sysctl

- block:

  - name: sysctl | Set facts platform.
    set_fact:
      platform_allow_os_families: [ "RedHat", "Test" ]
      platform_allow_distributions:

  - name: sysctl | Check the platform.
    include: "platform.yml"

  tags:
  - always
  - sysctl-os-family

- name: sysctl | Updating /etc/sysctl.conf
  template:
    src: "etc/sysctl.conf.j2"
    dest: "{{ prefix_dir|d('') }}/etc/sysctl.conf"
    owner: "{{ test_owner|d('root') }}"
    group: "{{ test_group|d('root') }}"
    mode: "0644"
    backup: yes
  tags:
  - sysctl

