---
# tasks file for epel
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- block:

  - name: epel | Install the epel.
    yum:
      name: "{{ epel_package_name|d('epel-release') }}"
      state: latest
      update_cache: "{{ epel_update_cache|d(true) }}"
    notify:
    - epel-yum-clean-metadata

  - name: epel | Refresh yum metadata
    meta: flush_handlers
  
  when: tests_run|d(false) == false
        and platforms_supported|d(false) == true
  tags:
  - epel
  - epel-install
