---
# dropins.yml tasks file for sudo
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- block:

  - name: "sudo | Dropin '{{ sudo_sudoers_dropin_file.name|d('???') }}' to '{{ _dropin_dir_path }}'."
    template:
      src: "etc/sudoers.dropin.j2"
      dest: "{{ '%s/%s'|format(_dropin_dir_path,
                sudo_sudoers_dropin_file.name) }}"
      owner: "{{ tests_owner|d(
                 sudo_sudoers_dropin_file.owner|d(
                 sudo_sudoers_dropin_file_owner|d(
                 _dropin_file_owner))) }}"
      group: "{{ tests_group|d(
                 sudo_sudoers_dropin_file.group|d(
                 sudo_sudoers_dropin_file_group|d(
                 _dropin_file_group))) }}"
      mode: "{{ sudo_sudoers_dropin_file.mode|d(
                sudo_sudoers_dropin_file_mode|d(
                _dropin_file_mode)) }}"
      backup: "{{ tests_run|d(false) == false }}"
      validate: "{{ _validate_command }}"
    tags:
    - sudo-sudores

  vars:
    _dropin_dir_path: "{{
      '%s%s'|format(tests_prefix_dir|d(''),
      sudo_sudoers_dropins_dir.path|d(
      sudo_sudoers_dropins_dir|d('/etc/sudoers.d'))) }}"
    _dropin_file_owner: "{{
      sudo_sudoers_dropins_dir.owner|d(
      sudo_sudoers_dropins_dir_owner|d(
      sudo_sudoers_file.owner|d(
      sudo_sudoers_file_owner|d('root')))) }}"
    _dropin_file_group: "{{
      sudo_sudoers_dropins_dir.group|d(
      sudo_sudoers_dropins_dir_group|d(
      sudo_sudoers_file.group|d(
      sudo_sudoers_file_group|d('wheel')))) }}"
    _dropin_file_mode: "{{
      sudo_sudoers_file.mode|d(
      sudo_sudoers_file_mode|d('0440')) }}"
    _validate_command: "{{
      sudo_sodoers_validate_command|d(omit)
      if tests_run|d(false) == false
      and sudo_sodoers_validate_command|d('')|string|trim|length > 0
      else omit }}"
  tags:
  - sudo

