---
# tasks file for sudo

- name: sudo | Include OS/Distribution specific variables.
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
  - "{{ '%s-%s.yml'|format(os_spec_os_family,os_spec_os_distribution) }}"
  - "{{ '%s.yml'|format(os_spec_os_family) }}"
  - "default.yml"
  tags: 
  - sudo
  - sudo-include-vars
  
- name: "sudo | Install the sudo."
  include: "{{ item }}"
  with_first_found:
  - "{{ '%s-%s.yml'|format(os_spec_os_family,os_spec_os_distribution) }}"
  - "{{ '%s.yml'|format(os_spec_os_family) }}"
  - "default.yml"
  tags:
  - sudo
  - sudo-install

- name: "sudo | Updating /etc/sudoers"
  template:
    src: "etc/sudoers.j2"
    dest: "{{ '%s%s'|format(prefix_dir|d(''),sudo_sudoers_file|d('/etc/sudoers')) }}"
    owner: "{{ test_owner|d(sudo_sudoers_file_owner|d('root')) }}"
    group: "{{ test_group|d(sudo_sudoers_file_group|d('wheel')) }}"
    mode: "{{ sudo_sudoers_file_mode|d('0440') }}"
    backup: yes
    validate: "{{ sudo_sodoers_validate_command
                  if test_run|d(none) is none
                  and sudo_sodoers_validate_command|d(none) is not none
                  else none }}"
  tags:
  - sudo
  - sudo-sudores

