---
# tasks file for sudo
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- name: "sudo | Include OS/Distribution specific variables."
  include_vars: "{{ _include_vars_file }}"
  ignore_errors: yes
  with_first_found:
  - files:
    - "{{ 'vars/vars_%s-%s.yml'|format(
          ansible_os_family|d('*')|lower,
          ansible_distribution|d('*')|lower) }}"
    - "{{ 'vars/vars_%s.yml'|format(ansible_os_family|d('*')|lower) }}"
    - "vars/vars_default.yml"
    skip: yes
  loop_control:
    loop_var: _include_vars_file
  tags:
  - sudo
  - sudo-include-vars

- name: "sudo | Install the logrotate."
  include: "{{ _include_tasks_file }}"
  with_first_found:
  - files:
    - "{{ 'tasks/tasks_%s-%s.yml'|format(
          ansible_os_family|d('*')|lower,
          ansible_distribution|d('*')|lower) }}"
    - "{{ 'tasks/tasks_%s.yml'|format(ansible_os_family|d('*')|lower) }}"
    - "tasks/tasks_default.yml"
    skip: yes
  loop_control:
    loop_var: _include_tasks_file
  tags:
  - sudo
  - sudo-install

- name: "sudo | Updating /etc/sudoers"
  template:
    src: "etc/sudoers.j2"
    dest: "{{ '%s%s'|format(tests_prefix_dir|d(''),sudo_sudoers_file|d('/etc/sudoers')) }}"
    owner: "{{ tests_owner|d(sudo_sudoers_file_owner|d('root')) }}"
    group: "{{ tests_group|d(sudo_sudoers_file_group|d('wheel')) }}"
    mode: "{{ sudo_sudoers_file_mode|d('0440') }}"
    backup: "{{ tests_run|d(false) == false }}"
    validate: "{{ sudo_sodoers_validate_command
                  if tests_run|d(false) == false
                  and sudo_sodoers_validate_command|d(none) is not none
                  else none }}"
  tags:
  - sudo
  - sudo-sudores

