---
# tasks file for sudo
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- block:

  - name: "sudo | The path of this role."
    command: echo {{ role_path|quote }}
    register: from_role_path
    changed_when: no
    check_mode: no

  - name: "sudo | Platform specific initialization processing."
    include_role:
      name: platforms
      tasks_from: setup

  tags:
  - sudo
  - sudo-setup

- block:

  - name: "sudo | Updating '{{ _sudoers_file }}'."
    template:
      src: "etc/sudoers.j2"
      dest: "{{ '%s%s'|format(tests_prefix_dir|d(''),_sudoers_file) }}"
      owner: "{{ tests_owner|d(_sudoers_file_owner) }}"
      group: "{{ tests_group|d(_sudoers_file_group) }}"
      mode: "{{ _sudoers_file_mode }}"
      backup: "{{ tests_run|d(false)|bool == false }}"
      validate: "{{ _sudoers_validate }}"
    vars:
      sudoers_defaults: "{{ sudo_sudoers_defaults|d([]) }}"
      sudoers_rules: "{{ sudo_sudoers_rules|d([]) }}"
      sudoers_aliases:
        host: "{{ sudo_sudoers_host_aliases|d([]) }}"
        user: "{{ sudo_sudoers_user_aliases|d([]) }}"
        runas: "{{ sudo_sudoers_runas_aliases|d([]) }}"
        command: "{{ sudo_sudoers_cmnd_aliases|d([]) }}"
      sudoers_dropins_dir: "{{ _sudoers_dropins_dir }}"
    tags:
    - sudo-sudores

  - name: "sudo | Process {{ _sudoers_dropins_dir }}."
    include: 'dropins.yml'
    static: yes
    with_items: "{{
      sudo_sudoers_dropins|d([])
      if _sudoers_dropins_dir|d('')|is_dir
      else [] }}"
    loop_control:
      loop_var: sudo_sudoers_dropin_file
    when: sudo_sudoers_dropins_dir|d('')|string|
          trim|lower|match('^(no|false)$') == false
          and sudo_sudoers_dropin_file is mapping
          and sudo_sudoers_dropin_file.name is string
          and sudo_sudoers_dropin_file.name|trim|length > 0
    tags:
    - sudo-dropins

  vars:
    _sudoers_file: "{{
      sudo_sudoers_file.path|trim
      if sudo_sudoers_file|d(none) is mapping
      and sudo_sudoers_file.path|d(none) is string
      and sudo_sudoers_file.path|trim|length > 0
      else sudo_sudoers_file|trim
      if sudo_sudoers_file|d(none) is string
      and sudo_sudoers_file|trim|length > 0
      else '/etc/sudoers' }}"
    _sudoers_file_owner: "{{
      sudo_sudoers_file.owner|trim
      if sudo_sudoers_file|d(none) is mapping
      and sudo_sudoers_file.owner|d(none) is string
      and sudo_sudoers_file.owner|trim|length > 0
      else sudo_sudoers_file_owner|trim
      if sudo_sudoers_file_owner|d(none) is string
      and sudo_sudoers_file_owner|trim|length > 0
      else 'root' }}"
    _sudoers_file_group: "{{
      sudo_sudoers_file.hroup|trim
      if sudo_sudoers_file|d(none) is mapping
      and sudo_sudoers_file.group|d(none) is string
      and sudo_sudoers_file.group|trim|length > 0
      else sudo_sudoers_file_group|trim
      if sudo_sudoers_file_group|d(none) is string
      and sudo_sudoers_file_group|trim|length > 0
      else sudo_administrators_group|d('wheel') }}"
    _sudoers_file_mode: "{{
      '%04o'|format(
      sudo_sudoers_file.mode|int(base=8)
      if sudo_sudoers_file|d(none) is mapping
      and sudo_sudoers_file.mode|d(none) is not none
      and sudo_sudoers_file.mode|string|trim|length > 0
      else sudo_sudoers_file_mode|int(base=8)
      if sudo_sudoers_file_mode|d(none) is not none
      and sudo_sudoers_file_mode|string|trim|length > 0
      else '0440'|int(base=8)) }}"
    _sudoers_dropins_dir: "{{
      sudo_sudoers_dropins_dir.path|trim
      if sudo_sudoers_dropins_dir|d(none) is mapping
      and sudo_sudoers_dropins_dir.path|d(none) is string
      and sudo_sudoers_dropins_dir.path|trim|length > 0
      else sudo_sudoers_dropins_dir|trim
      if sudo_sudoers_dropins_dir|d(none) is string
      and sudo_sudoers_dropins_dir|trim|length > 0
      and sudo_sudoers_dropins_dir|
          trim|lower|match('^(no|false)$') == false
      else '/etc/sudoers.d'
      if sudo_sudoers_dropins_dir|d(none) is none
      or sudo_sudoers_dropins_dir|string
         trim|lower|match('^(no|false)$') == false
      else '' }}"
    _sudoers_validate: "{{
      sudo_sodoers_validate_command|trim
      if tests_run|d(false)|bool == false
      and sudo_sodoers_validate_command|d(none) is string
      and sudo_sodoers_validate_command|trim|length > 0
      else omit }}"
  tags:
  - sudo

