---
# tasks file for sudo of "redhat"
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- name: "sudo | redhat | Install the sudo"
  yum:
    name: "{{
        _sudo_package.name|trim
        if _sudo_package|d(none) is mapping
        and _sudo_package.name|d(none) is string
        and _sudo_package.name|trim|length > 0
        else _sudo_package|trim }}"
    state: "{{
        _sudo_package.state|trim
        if _sudo_package|d(none) is mapping
        and _sudo_package.state|d(none) is string
        and _sudo_package.state|trim|length > 0
        else 'latest' }}"
  with_items: "{{ sudo_install_packages|d(['sudo']) }}"
  loop_control:
    loop_var: _sudo_package
  when: tests_run|d(false)|bool == false
        and _sudo_package|d(none) is not none
        and _sudo_package|string|trim|length > 0
  tags:
  - sudo
  - sudo-install
  - sudo-redhat
  - sudo-redhat-install

- name: "sudo | redhat | Create a dropins dir."
  file:
    path: "{{ '%s%s'|format(tests_prefix_dir|d(''),_dropins_dir) }}"
    state: directory
    owner: "{{ tests_owner|d(_dropins_dir_owner) }}"
    group: "{{ tests_group|d(_dropins_dir_group) }}"
    mode: "{{ _dropins_dir_mode }}"
  vars:
    _dropins_dir: "{{
      sudo_sudoers_dropins_dir.path|trim
      if sudo_sudoers_dropins_dir|d(none) is mapping
      and sudo_sudoers_dropins_dir.path|d(none) is string
      and sudo_sudoers_dropins_dir.path|trim|length > 0
      else sudo_sudoers_dropins_dir|trim
      if sudo_sudoers_dropins_dir|d(none) is string
      and sudo_sudoers_dropins_dir|trim|length > 0
      and sudo_sudoers_dropins_dir|
          trim|lower|match('^(no|false)$') == false
      else '/etc/sudoers.d' }}"
    _dropins_dir_owner: "{{
      sudo_sudoers_dropins_dir.owner|trim
      if sudo_sudoers_dropins_dir|d(none) is mapping
      and sudo_sudoers_dropins_dir.owner|d(none) is string
      and sudo_sudoers_dropins_dir.owner|trim|length > 0
      else sudo_sudoers_dropins_dir_owner|trim
      if sudo_sudoers_dropins_dir_owner|d(none) is string
      and sudo_sudoers_dropins_dir_owner|trim|length > 0
      else 'root' }}"
    _dropins_dir_group: "{{
      sudo_sudoers_dropins_dir.group|trim
      if sudo_sudoers_dropins_dir|d(none) is mapping
      and sudo_sudoers_dropins_dir.group|d(none) is string
      and sudo_sudoers_dropins_dir.group|trim|length > 0
      else sudo_sudoers_dropins_dir_group|trim
      if sudo_sudoers_dropins_dir_group|d(none) is string
      and sudo_sudoers_dropins_dir_group|trim|length > 0
      else sudo_administrators_group|d('wheel') }}"
    _dropins_dir_mode: "{{
      '%04o'|format(
      sudo_sudoers_dropins_dir.mode|int(base=8)
      if sudo_sudoers_dropins_dir|d(none) is mapping
      and sudo_sudoers_dropins_dir.mode|d(none) is string
      and sudo_sudoers_dropins_dir.mode|trim|length > 0
      else sudo_sudoers_dropins_dir_mode|int(base=8)
      if sudo_sudoers_dropins_dir_mode|d(none) is not none
      and sudo_sudoers_dropins_dir_mode|string|trim|length > 0
      else '0770'|int(base=8)) }}"
  tags:
  - sudo
  - sudo-install
  - sudo-redhat
  - sudo-redhat-install
